"""add_kms_key_id_to_ballots

Revision ID: 0b29e62ea43e
Revises: e81b37ed6599
Create Date: 2026-02-01 18:52:46.635922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b29e62ea43e'
down_revision: Union[str, Sequence[str], None] = 'e81b37ed6599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballots', sa.Column('kms_key_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ballots', 'kms_key_id')
    # ### end Alembic commands ###
