"""initial_schema

Revision ID: 5e10cbf603d7
Revises: 
Create Date: 2026-01-25 13:59:58.367001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e10cbf603d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ballots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('measure', sa.String(length=255), nullable=False),
    sa.Column('allow_write_in', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ballot_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ballot_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('options')
    op.drop_table('ballots')
    # ### end Alembic commands ###
