"""add_encryption_and_id_voting

Revision ID: e81b37ed6599
Revises: a56fca33e4c6
Create Date: 2026-01-31 21:19:25.431751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81b37ed6599'
down_revision: Union[str, Sequence[str], None] = 'a56fca33e4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballots', sa.Column('encrypted_measure', sa.String(length=512), nullable=False))
    op.add_column('ballots', sa.Column('encrypted_dek', sa.String(length=1024), nullable=False))
    op.drop_column('ballots', 'measure')
    op.add_column('options', sa.Column('encrypted_text', sa.String(length=512), nullable=False))
    op.add_column('options', sa.Column('is_write_in', sa.Boolean(), nullable=False))
    op.drop_column('options', 'text')
    op.add_column('votes', sa.Column('option_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'votes', 'options', ['option_id'], ['id'])
    op.drop_column('votes', 'option_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('option_text', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'option_id')
    op.add_column('options', sa.Column('text', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('options', 'is_write_in')
    op.drop_column('options', 'encrypted_text')
    op.add_column('ballots', sa.Column('measure', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('ballots', 'encrypted_dek')
    op.drop_column('ballots', 'encrypted_measure')
    # ### end Alembic commands ###
